"""renamme address

Revision ID: 4af540465458
Revises: f4f425e46e4e
Create Date: 2025-09-18 01:45:50.624013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4af540465458'
down_revision = 'f4f425e46e4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address', new_column_name='location')
    # op.drop_column('departments', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('departments', sa.Column('address', sa.VARCHAR(), nullable=True))
    op.alter_column('departments', 'location', new_column_name='address')
    # ### end Alembic commands ###
